Add auto deploy on Kosmos

diff --git a/.github/workflows/master_push.workflow.yaml b/.github/workflows/master_push.workflow.yaml
--- a/.github/workflows/master_push.workflow.yaml
+++ b/.github/workflows/master_push.workflow.yaml
@@ -4,62 +4,65 @@ on:
   push:
     branches:
       - master
+
 env:
   NODE_VERSION: "14"
   DOCKER_IMAGE: "kuzzleio/kepler:latest"
 
 jobs:
-  # lint:
-  #   name: Lint ${{ matrix.project }}
-  #   runs-on: ubuntu-18.04
-  #   strategy:
-  #     fail-fast: true
-  #     matrix: 
-  #       project: ['kepler', 'kepler-companion']
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - name: Cache node modules
-  #       uses: actions/cache@v2
-  #       env:
-  #         cache-name: cache-node-modules
-  #       with:
-  #         path: ~/.npm
-  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-build-${{ env.cache-name }}-
-  #           ${{ runner.os }}-build-
-  #           ${{ runner.os }}-
-  #     - uses: actions/setup-node@v1.4.4
-  #       with:
-  #         node-version: "12"
-  #     - name: Run linter
-  #       run: npm ci --prefix ${{ matrix.project }} && npm run test:lint --prefix ${{ matrix.project }}
-  # publish-kepler-image:
-  #   name: Build and publish Kepler Docker image on Dockerhub
-  #   runs-on: ubuntu-18.04
-  #   needs: [lint]
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - name: Set up QEMU
-  #       uses: docker/setup-qemu-action@v1
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v1
-  #     - name: Login to Docker Hub
-  #       uses: docker/login-action@v1
-  #       with:
-  #         username: ${{ secrets.DOCKER_USERNAME }}
-  #         password: ${{ secrets.DOCKER_PASSWORD }}
-  #     - name: Build and push
-  #       uses: docker/build-push-action@v2
-  #       with:
-  #         push: true
-  #         tags: ${{ env.DOCKER_IMAGE }}
-  #         file: kepler/Dockerfile
-  #         context: kepler
+  lint:
+    name: Lint ${{ matrix.project }}
+    runs-on: ubuntu-18.04
+    strategy:
+      fail-fast: true
+      matrix: 
+        project: ['kepler', 'kepler-companion']
+    steps:
+      - uses: actions/checkout@v2
+      - name: Cache node modules
+        uses: actions/cache@v2
+        env:
+          cache-name: cache-node-modules
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+      - uses: actions/setup-node@v1.4.4
+        with:
+          node-version: "12"
+      - name: Run linter
+        run: npm ci --prefix ${{ matrix.project }} && npm run test:lint --prefix ${{ matrix.project }}
+
+  publish-kepler-image:
+    name: Build and publish Kepler Docker image on Dockerhub
+    runs-on: ubuntu-18.04
+    needs: [lint]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+      - name: Login to Docker Hub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build and push
+        uses: docker/build-push-action@v2
+        with:
+          push: true
+          tags: ${{ env.DOCKER_IMAGE }}
+          file: kepler/Dockerfile
+          context: kepler
+
   deploy-kepler-on-kosmos:
     name: Deploy latest Kepler image on Kosmos
     runs-on: ubuntu-18.04
-    # needs: [publish-kepler-image]
+    needs: [publish-kepler-image]
     environment: Kosmos
     steps:
       - uses: actions/checkout@v2
@@ -77,24 +80,17 @@ jobs:
           SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
           SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
           SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}
-      - name: Download the Helm values file from Kosmos repository
-        run: |
-          curl -H "Authorization: token ${{ secrets.ACCESS_TOKEN_CI }}" \
-            -H 'Accept: application/vnd.github.v3.raw' \
-            -o kepler.yaml \
-            -L https://api.github.com/repos/kuzzleio/kosmos/contents/tf/helm_values/kepler/kepler.yaml
-          cat kepler.yaml
       - name: Install Helm 3
         run: |
           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
-      - name: List Helm releases
+      - name: Deploy Kepler using Helm
         run: |
           helm repo add kuzzle https://kuzzleio.github.io/helm-charts/
-#          if helm upgrade kepler kuzzle/kuzzle --install --namespace analytics --set image.tag="$COMMIT_SHORT_SHA" --wait --timeout 1m; then
-#            echo "deployment succeeded!"
-#          else
-#            echo "DEPLOYMENT FAILED! TRYING TO ROLLBACK"
-#            helm rollback kepler --namespace analytics
-#            exit 1
-#          fi
+          if helm upgrade kepler kuzzle/kuzzle --install --namespace analytics --reuse-values --force --wait --timeout 1m; then
+            echo "deployment succeeded!"
+          else
+            echo "DEPLOYMENT FAILED! TRYING TO ROLLBACK"
+            helm rollback kepler --namespace analytics
+            exit 1
+          fi
       
