Test Helm values fetching from other repo

diff --git a/.github/workflows/master_push.workflow.yaml b/.github/workflows/master_push.workflow.yaml
--- a/.github/workflows/master_push.workflow.yaml
+++ b/.github/workflows/master_push.workflow.yaml
@@ -79,14 +79,22 @@ jobs:
           SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}
       - name: Download the Helm values file from Kosmos repository
         run: |
-          curl -H "Authorization: token $TOKEN" \
+          curl -H "Authorization: token ${{ github.token }}" \
             -H 'Accept: application/vnd.github.v3.raw' \
             -o kepler.yaml \
             -L https://api.github.com/repos/kuzzleio/kosmos/contents/tf/helm_values/kepler/kepler.yaml?ref=master
+          cat kepler.yaml
       - name: Install Helm 3
         run: |
           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
       - name: List Helm releases
         run: |
-          helm list -n analytics --kubeconfig ./kubeconfig
+          helm repo add kuzzle https://kuzzleio.github.io/helm-charts/
+#          if helm upgrade kepler kuzzle/kuzzle --install --namespace analytics --set image.tag="$COMMIT_SHORT_SHA" --wait --timeout 1m; then
+#            echo "deployment succeeded!"
+#          else
+#            echo "DEPLOYMENT FAILED! TRYING TO ROLLBACK"
+#            helm rollback kepler --namespace analytics
+#            exit 1
+#          fi
       
